repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: '^images/.*$'
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: poetry run ruff check --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: poetry run ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: pyright
        name: pyright
        language: system
        entry: poetry run pyright
        types: [python, pyi, jupyter]
        pass_filenames: false
        stages: [pre-commit, pre-merge-commit, pre-push, manual]
      - id: pytest
        name: pytest
        language: system
        entry: poetry run pytest
        types: [python]
        pass_filenames: false
        stages: [pre-commit, pre-merge-commit, pre-push, manual]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [push]
